# Generated by Django 6.1.1 on 2026-09-19 17:24

import django_mongodb_backend.fields
import tweet.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=tweet.storage.ImageKitStorage(), upload_to='photos/'),
        ),
    ]
