"""
Django settings for tweeter project.

Generated by 'django-admin startproject' using Django 6.1.1.
"""

from pathlib import Path
import os

from dotenv import load_dotenv

load_dotenv()

# --------------------------------------------------

# BASE DIRECTORY

# --------------------------------------------------

BASE_DIR = Path(__file__).resolve().parent.parent
# --------------------------------------------------

# SECURITY

# --------------------------------------------------

SECRET_KEY = os.getenv('SECRET_KEY')

DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
'localhost',
'127.0.0.1',
'.onrender.com',
]

# --------------------------------------------------

# APPLICATIONS

# --------------------------------------------------

INSTALLED_APPS = [
'django.contrib.admin',
'django.contrib.auth',
'django.contrib.contenttypes',
'django.contrib.sessions',
'django.contrib.messages',
'django.contrib.staticfiles',


'tweet',

]

# --------------------------------------------------

# MIDDLEWARE

# --------------------------------------------------

MIDDLEWARE = [
'django.middleware.security.SecurityMiddleware',


# WhiteNoise should come after SecurityMiddleware
'whitenoise.middleware.WhiteNoiseMiddleware',

'django.contrib.sessions.middleware.SessionMiddleware',
'django.middleware.common.CommonMiddleware',
'django.middleware.csrf.CsrfViewMiddleware',
'django.contrib.auth.middleware.AuthenticationMiddleware',
'django.contrib.messages.middleware.MessageMiddleware',
'django.middleware.clickjacking.XFrameOptionsMiddleware',


]

# --------------------------------------------------

# URL CONFIGURATION

# --------------------------------------------------

ROOT_URLCONF = 'tweeter.urls'

# --------------------------------------------------

# TEMPLATES

# --------------------------------------------------

TEMPLATES = [
{
'BACKEND': 'django.template.backends.django.DjangoTemplates',


    'DIRS': [
        BASE_DIR / 'templates'
    ],

    'APP_DIRS': True,

    'OPTIONS': {
        'context_processors': [
            'django.template.context_processors.request',
            'django.contrib.auth.context_processors.auth',
            'django.contrib.messages.context_processors.messages',
        ],
    },
},

]

# --------------------------------------------------

# WSGI

# --------------------------------------------------

WSGI_APPLICATION = 'tweeter.wsgi.application'

# --------------------------------------------------

# DATABASE

# --------------------------------------------------

DATABASES = {
'default': {
'ENGINE': 'django.db.backends.sqlite3',
'NAME': BASE_DIR / 'db.sqlite3',
}
}

# --------------------------------------------------

# PASSWORD VALIDATION

# --------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
{
'NAME':
'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
},
{
'NAME':
'django.contrib.auth.password_validation.MinimumLengthValidator',
},
{
'NAME':
'django.contrib.auth.password_validation.CommonPasswordValidator',
},
{
'NAME':
'django.contrib.auth.password_validation.NumericPasswordValidator',
},
]

# --------------------------------------------------

# INTERNATIONALIZATION

# --------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# --------------------------------------------------

# STATIC FILES

# --------------------------------------------------

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
BASE_DIR / 'static'
]

# --------------------------------------------------

# MEDIA FILES

# --------------------------------------------------

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'

# --------------------------------------------------

# AUTHENTICATION

# --------------------------------------------------

LOGIN_URL = '/login/'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

# --------------------------------------------------

# EMAIL

# --------------------------------------------------

# Email configuration can be added later when

# your application needs to send real emails.

# --------------------------------------------------

# PRODUCTION SECURITY

# --------------------------------------------------

if not DEBUG:
    SECURE_SSL_REDIRECT = True

# Only send session cookies over HTTPS
    SESSION_COOKIE_SECURE = True

# Only send CSRF cookies over HTTPS
    CSRF_COOKIE_SECURE = True
